#!/bin/sh
set -e
case "$1" in
     configure)
     ln -s /usr/share/pyshared/posanal /usr/lib/python3.3/dist-packages/
     ;;

     abort-upgrade|abort-remove|abort-deconfigure)
     rm -f /usr/lib/python3.3/dist-packages/posanal
     ;;

     *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
     ;;
esac
exit 0
